; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_filters = 
	direct

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_filters =
	direct
upload_speed = 921600
lib_ignore = AsyncTCP_RP2040W
lib_deps = 
	mikem/RadioHead@^1.120
	adafruit/Adafruit BME280 Library@^2.2.4
	bblanchon/ArduinoJson@^7.3.0
	me-no-dev/ESPAsyncWebServer@^3.6.0
	sparkfun/SparkFun Indoor Air Quality Sensor - ENS160@^1.1.0
	sparkfun/SparkFun Qwiic Humidity AHT20@^1.0.3
	buelowp/sunset @ ^1.1.7
build_src_filter = +<*> -<NexUpload.cpp>
